DROP TABLE if exists ITEMS;
DROP TABLE if exists USERS;
DROP TABLE if exists BIDS;
DROP TABLE if exists CATEGORIES;

CREATE TABLE USERS
(
  UserID VARCHAR(300),
  Location VARCHAR(500),
  Rating INTEGER,
  Country VARCHAR(300),
  PRIMARY KEY (UserID)
);

CREATE TABLE ITEMS
(
 ItemID INTEGER ,
 Name VARCHAR(300),
 Currently DECIMAL,
 Buy_Price DECIMAL,
 First_Bid DECIMAL,
 Number_of_Bids INTEGER ,
 Started TIMESTAMP ,
 Ends TIMESTAMP ,
 Description TEXT ,
 SellerID VARCHAR(300) ,
 PRIMARY KEY (ItemID),
 FOREIGN KEY (SellerID) REFERENCES USERS(UserID)
);

CREATE TABLE CATEGORIES
(
 Category VARCHAR(300) ,
 ItemID INTEGER ,
 PRIMARY KEY(ItemID, Category)
 FOREIGN KEY (ItemID) REFERENCES ITEMS(ItemID)
);

CREATE TABLE BIDS
(
 ItemID INTEGER ,
 BidderID VARCHAR(300) ,
 Time TIMESTAMP ,
 Amount DECIMAL ,
 PRIMARY KEY(ItemID, BidderID, Time)
 FOREIGN KEY (ItemID) REFERENCES ITEMS(ItemID),
 FOREIGN KEY (BidderID) REFERENCES USERS(UserID)
);
